"""
simulators.py
=============

Simulation of the point-process Interacting Particle System underlying
our filtering experiments, together with exact Bayesian filters for the
interaction matrix W.

We follow the setup of Cormier (MVA notes, Section 12) and of the
companion document `rhu_stage_preparation.pdf`.

Two settings
------------
* `Simulator2`  : two-neuron case with a binary coupling J in {0, 1},
                  prior Ber(1-p0) on J.
* `SimulatorN`  : n-neuron case with binary connectivity matrix
                  W in {0,1}^{n x n} and factorised posterior.

Conventions
-----------
* `f(v)` is the (bounded) intensity function. By default: sigmoid.
* `f_max` is a strict upper bound used for thinning.
* `theta` is the rate of the exogenous driving Poisson process
  (only in the two-neuron case).
* All quantities are returned on a regular time grid of step `dt`
  so that figures can be produced easily.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Callable, Tuple
import itertools
import numpy as np


# ---------------------------------------------------------------------
# Intensity functions
# ---------------------------------------------------------------------

def sigmoid(v: np.ndarray | float) -> np.ndarray | float:
    """Bounded, smooth intensity function, values in (0, 1)."""
    return 1.0 / (1.0 + np.exp(-v))


# =====================================================================
# Two-neuron case: J in {0, 1}
# =====================================================================

@dataclass
class Simulator2:
    """
    Two-neuron filtering simulator.

    Model
    -----
    * Ntilde is a Poisson process of rate ``theta`` (exogenous neuron 1).
    * V is the potential of neuron 2, with dynamics
          dV_t = J d\\tilde N_t - V_{t-} dN_t,  V_0 = 0.
    * N has stochastic intensity f(V_{t-}) (observed neuron 2).
    * J is a random variable with prior  P(J=1) = 1 - p0,
                                         P(J=0) = p0.

    Observation: the filtration generated by both (Ntilde, N).

    The simulator also evolves in parallel the posterior
        p_t^1 = P(J = 1 | G_t)
    whose dynamics are derived in the companion document.

    Parameters
    ----------
    theta     : rate of Ntilde.
    p0        : prior probability of {J = 0}; so P(J=1) = 1 - p0.
    true_J    : true value of J used to generate data (0 or 1).
    f         : intensity function.
    f_max     : upper bound on f used for thinning.
    dt        : time step of the output grid (ODE integration step).
    T         : final time.
    seed      : RNG seed.
    """

    theta:  float = 1.0
    p0:     float = 0.5
    true_J: int   = 1
    f:      Callable[[float], float] = field(default=sigmoid)
    f_max:  float = 1.0
    dt:     float = 1e-2
    T:      float = 200.0
    seed:   int | None = None

    # ---------------------------------------------------------------
    def run(self) -> dict:
        rng = np.random.default_rng(self.seed)
        f, fmax = self.f, self.f_max
        dt, T   = self.dt, self.T

        # State
        t   = 0.0
        V   = 0.0   # true potential (uses true_J)
        V0  = 0.0   # hypothesis potential under J=0
        V1  = 0.0   # hypothesis potential under J=1
        p1  = 1.0 - self.p0              # P(J=1 | G_t)

        # Logs (regular grid in time)
        times = [t]
        post  = [p1]
        pot   = [V]
        spikes_N     = []   # times where N fires
        spikes_Nt    = []   # times where Ntilde fires

        while t < T:
            # Next candidates
            tau_tilde = rng.exponential(1.0 / self.theta)
            tau_N     = rng.exponential(1.0 / fmax)
            t_tilde   = t + tau_tilde
            t_N       = t + tau_N
            t_next    = min(t_tilde, t_N, T)

            # --- Integrate posterior ODE between jumps
            while t + dt < t_next:
                # dp1/dt = p1 (1 - p1) (f(V0) - f(V1))
                dp = p1 * (1.0 - p1) * (f(V0) - f(V1))
                p1 = np.clip(p1 + dp * dt, 1e-12, 1 - 1e-12)
                t += dt
                times.append(t); post.append(p1); pot.append(V)
            # Small remainder up to t_next
            rem = t_next - t
            if rem > 0:
                dp = p1 * (1.0 - p1) * (f(V0) - f(V1))
                p1 = np.clip(p1 + dp * rem, 1e-12, 1 - 1e-12)
                t = t_next
                times.append(t); post.append(p1); pot.append(V)

            if t >= T:
                break

            # --- Event at t_next
            if t_next == t_tilde:
                # Jump of Ntilde: V gains true_J; V1 gains 1, V0 unchanged.
                V  += self.true_J
                V1 += 1.0
                spikes_Nt.append(t)
            else:
                # Candidate jump of N accepted with prob f(V)/f_max
                if rng.uniform() < f(V) / fmax:
                    spikes_N.append(t)
                    # Bayesian update at jump of N
                    num = f(V1) * p1
                    den = f(V0) * (1.0 - p1) + f(V1) * p1
                    p1 = num / den
                    # Reset potentials
                    V = 0.0; V0 = 0.0; V1 = 0.0

        return {
            "times":     np.asarray(times),
            "posterior": np.asarray(post),
            "potential": np.asarray(pot),
            "spikes_N":  np.asarray(spikes_N),
            "spikes_Nt": np.asarray(spikes_Nt),
            "true_J":    self.true_J,
            "p0":        self.p0,
        }


# =====================================================================
# n-neuron case with factorised posterior
# =====================================================================

@dataclass
class SimulatorN:
    """
    n-neuron simulator with binary connectivity matrix W in {0,1}^{n x n}
    (zero diagonal).  Each neuron i has potential V_i with dynamics

        dV_i = sum_{j != i} W_{j i} dN_j  -  V_{i, t-} dN_i,

    and stochastic intensity f(V_i).  We observe all spike trains N_i
    and maintain a factorised posterior over the incoming edges
    W_i = (W_{j i})_{j != i} in {0, 1}^{n-1}.
    """

    n:       int   = 5
    W_true:  np.ndarray | None = None   # if None, sampled at run
    p_edge:  float = 0.5                # Bernoulli edge density (prior & truth)
    f:       Callable[[float], float] = field(default=sigmoid)
    f_max:   float = 1.0
    dt:      float = 1e-2
    T:       float = 500.0
    log_stride: int = 10                # subsample stored states
    seed:    int | None = None

    def _build_config_space(self) -> np.ndarray:
        """Return an (n, K, n) tensor: W_spaces[i, k, :] = k-th candidate
        row of incoming edges into neuron i (with W[i,i] = 0 enforced).
        Here K = 2^{n-1}."""
        n = self.n
        K = 2 ** (n - 1)
        W_spaces = np.zeros((n, K, n), dtype=np.int8)
        for i in range(n):
            rows = []
            for bits in itertools.product([0, 1], repeat=n - 1):
                row = list(bits)
                row.insert(i, 0)  # W[i,i] = 0
                rows.append(row)
            W_spaces[i] = np.asarray(rows, dtype=np.int8)
        return W_spaces

    # ---------------------------------------------------------------
    def run(self) -> dict:
        rng = np.random.default_rng(self.seed)
        f, fmax = self.f, self.f_max
        n, dt, T = self.n, self.dt, self.T

        # True connectivity
        if self.W_true is None:
            W_true = (rng.uniform(size=(n, n)) < self.p_edge).astype(np.int8)
            np.fill_diagonal(W_true, 0)
        else:
            W_true = np.array(self.W_true, dtype=np.int8)
            np.fill_diagonal(W_true, 0)

        # Configuration space and uniform prior
        W_spaces = self._build_config_space()     # (n, K, n)
        K = W_spaces.shape[1]
        p = np.full((n, K), 1.0 / K)              # posterior per neuron

        # Potentials
        V_true = np.zeros(n, dtype=np.float64)
        V_w    = np.zeros((n, K), dtype=np.float64)

        # Logs
        t = 0.0
        times_log = [t]
        posterior_log = [p.copy()]
        step = 0

        while t < T:
            # Candidate next jump (thinning upper bound across all neurons)
            tau = rng.exponential(1.0 / (n * fmax))
            t_next = min(t + tau, T)

            # --- ODE between jumps on every factor (vectorised over neurons)
            while t + dt < t_next:
                lam = f(V_w)                              # (n, K)
                lam_bar = np.sum(p * lam, axis=1, keepdims=True)  # (n, 1)
                p = p + p * (lam_bar - lam) * dt
                np.clip(p, 1e-14, None, out=p)
                p /= p.sum(axis=1, keepdims=True)
                t += dt
                step += 1
                if step % self.log_stride == 0:
                    times_log.append(t); posterior_log.append(p.copy())

            rem = t_next - t
            if rem > 0:
                lam = f(V_w)
                lam_bar = np.sum(p * lam, axis=1, keepdims=True)
                p = p + p * (lam_bar - lam) * rem
                np.clip(p, 1e-14, None, out=p)
                p /= p.sum(axis=1, keepdims=True)
                t = t_next
                times_log.append(t); posterior_log.append(p.copy())

            if t >= T:
                break

            # --- Candidate jump: pick neuron and accept/reject
            rates = f(V_true)
            total = rates.sum()
            if rng.uniform() < total / (n * fmax):
                # select which neuron spikes
                probs = rates / total
                i_spike = int(rng.choice(n, p=probs))

                # Bayesian update for i_spike's posterior
                w = f(V_w[i_spike])            # (K,)
                pp = p[i_spike] * w
                pp /= pp.sum()
                p[i_spike] = pp

                # Reset potentials of the spiking neuron
                V_true[i_spike] = 0.0
                V_w[i_spike, :] = 0.0

                # Propagate potentials to downstream neurons
                for j in range(n):
                    if j == i_spike:
                        continue
                    V_true[j] += W_true[i_spike, j]
                    V_w[j] += W_spaces[j, :, i_spike]

        return {
            "times":      np.asarray(times_log),
            "posterior":  np.stack(posterior_log, axis=0),  # (T', n, K)
            "W_true":     W_true,
            "W_spaces":   W_spaces,
        }


# ---------------------------------------------------------------------
# Helper: posterior mean and MAP of W from a SimulatorN run.
# ---------------------------------------------------------------------

def posterior_W_mean(posterior: np.ndarray, W_spaces: np.ndarray) -> np.ndarray:
    """
    Compute posterior mean of W given the per-neuron factor p[i].

    Parameters
    ----------
    posterior : (T', n, K) array of per-neuron posteriors.
    W_spaces  : (n, K, n) array of candidate configurations.

    Returns
    -------
    W_mean : (T', n, n) array where W_mean[t, j, i] = E[W_{j,i} | G_t].
    """
    # W_mean[t, j, i] = sum_k p[t, i, k] * W_spaces[i, k, j]
    return np.einsum("tik,ikj->tji", posterior, W_spaces.astype(float))
